var characters = [];
characters.push('hello');
characters.push('world');
console.log('characters: ', characters);
var mixed = [];
mixed.push('hello');
mixed.push(20);
console.log('mixed:', mixed);
var uid;
uid = 13;
console.log(uid);
uid = '12345';
console.log(uid);
var ninjaOne;
ninjaOne = { name: 'xjy', age: 22, belt: 'black' };
console.log(ninjaOne);
var circ = function (diameter) {
    return diameter * Math.PI;
};
console.log(circ(15));
